!includeurl https://raw.githubusercontent.com/gkatsikas/hypo-workflows/refs/heads/main/palette/hypo-palette.puml

hide footbox
!pragma teoz true

' =====================
' Global Theme
' =====================
!theme hacker

' =====================
' Global Styling
' =====================
' Fonts and basic colors
skinparam DefaultFontSize 20
skinparam defaultTextAlignment center
skinparam BackgroundColor #F0F0F0
skinparam DefaultFontColor black

' Arrow / Message Styling
skinparam ArrowColor black
skinparam SequenceMessageFontColor black
skinparam SequenceMessageFontSize 14

' Notes / Annotations Styling
skinparam NoteBackgroundColor #FEFECE
skinparam NoteBorderColor black

' Padding
skinparam BoxPadding 10
skinparam ParticipantPadding 10

' Actors shall have obvious outline
skinparam actor {
    BorderColor black
}

' =====================
' Logos
' =====================

' https://labs.etsi.org/rep/osl/code/org.etsi.osl.portal.web/-/raw/main/src/images/logo_clear.png
' https://raw.githubusercontent.com/openziti/ziti-doc/refs/heads/main/docusaurus/static/img/openziti-logo-light.svg
' https://raw.githubusercontent.com/kubernetes/kubernetes/refs/heads/master/logo/logo.png

' =====================
' Reusable Components
' =====================

' ETSI HypO Components
!unquoted procedure HYPO_LOGO_BOX()
box "<img:https://raw.githubusercontent.com/gkatsikas/hypo-workflows/refs/heads/main/images/logo_hypo_black.png{scale=0.3}>" #HYPO_GREEN_6
!endprocedure

!unquoted procedure END_HYPO_LOGO_BOX()
end box
!endprocedure

!unquoted procedure HYPO_BOX($name)
box "$name" #HYPO_BOX_COLOR
!endprocedure

!unquoted procedure HYPO_BOX_WHITE_TEXT($name)
box "<color:white>$name</color>" #HYPO_BOX_COLOR
!endprocedure

!unquoted procedure END_HYPO_BOX()
end box
!endprocedure

!unquoted procedure HYPO_SERVICE($name)
participant "$name" #HYPO_SERVICE_COLOR
!endprocedure

!unquoted procedure HYPO_DB($name)
database "$name" #HYPO_DB_COLOR
!endprocedure

!unquoted procedure HYPO_BUS($name)
skinparam queueBorderColor #black
queue "$name" #white
!endprocedure

' Zero-Trust Network Fabric Components
!unquoted procedure FABRIC_BOX_LOGO($name)
box "<img:https://raw.githubusercontent.com/gkatsikas/hypo-workflows/refs/heads/main/images/logo_openziti.png{scale=0.1}>\n$name" #FABRIC_BOX_COLOR
!endprocedure

!unquoted procedure END_FABRIC_BOX_LOGO()
end box
!endprocedure

!unquoted procedure FABRIC_BOX($name)
box "$name" #FABRIC_BOX_COLOR
!endprocedure

!unquoted procedure END_FABRIC_BOX()
end box
!endprocedure

!unquoted procedure FABRIC_CTRL($name)
skinparam participantBorderColor HYPO_PURPLE_1
participant "$name" #FABRIC_CTRL_COLOR
!endprocedure

!unquoted procedure FABRIC_CLIENT($name)
skinparam participantBorderColor HYPO_PURPLE_1
participant "$name" #FABRIC_CLIENT_COLOR
!endprocedure

' Remote Infrastructure Components
!unquoted procedure REMOTE_INFRA_BOX($name)
box "$name" #REMOTE_INFRA_BOX_COLOR
!endprocedure

!unquoted procedure END_REMOTE_INFRA_BOX()
end box
!endprocedure

' ETSI OpenSlice Components
!unquoted procedure OSL_LOGO_BOX()
box "<img:https://raw.githubusercontent.com/gkatsikas/hypo-workflows/refs/heads/main/images/logo_osl.png{scale=0.8}>" #OSL_COLOR_LIGHT
!endprocedure

!unquoted procedure END_OSL_LOGO_BOX()
end box
!endprocedure

!unquoted procedure OSL_INST($name)
skinparam participantBorderColor DarkOrange
participant "$name" #OSL_COLOR
!endprocedure

!unquoted procedure OSL_INST_LOGO()
skinparam participantBorderColor DarkOrange
participant "<img:https://raw.githubusercontent.com/gkatsikas/hypo-workflows/refs/heads/main/images/logo_osl.png{scale=0.8}>" #OSL_COLOR
!endprocedure

' Compute Clusters Components
!unquoted procedure CLUSTER_LOGO_BOX()
box "<img:https://raw.githubusercontent.com/kubernetes/kubernetes/refs/heads/master/logo/logo.png{scale=0.008}>" #CLUSTER_BOX_COLOR
!endprocedure

!unquoted procedure END_CLUSTER_LOGO_BOX()
end box
!endprocedure

!unquoted procedure CLUSTER_CTRL_LOGO($name)
skinparam collectionsBorderColor black
collections "<img:https://raw.githubusercontent.com/kubernetes/kubernetes/refs/heads/master/logo/logo.png{scale=0.008}>\n$name" #CLUSTER_CTRL_COLOR
!endprocedure

!unquoted procedure CLUSTER_CTRL($name)
skinparam collectionsBorderColor black
collections "$name" #CLUSTER_CTRL_COLOR
!endprocedure

!unquoted procedure CLUSTER_NODES_LOGO($name)
skinparam collectionsBorderColor black
collections "<img:https://raw.githubusercontent.com/kubernetes/kubernetes/refs/heads/master/logo/logo.png{scale=0.008}>\n$name" #CLUSTER_NODES_COLOR
!endprocedure

!unquoted procedure KEYCLOAK_LOGO($name)
skinparam collectionsBorderColor black
collections "<img:https://raw.githubusercontent.com/gkatsikas/hypo-workflows/refs/heads/user-registration/images/Keycloak-logo.png{scale=0.15}>\n$name" #White
!endprocedure

!unquoted procedure CLUSTER_NODES($name)
skinparam collectionsBorderColor black
collections "$name" #CLUSTER_NODES_COLOR
!endprocedure
